#! /usr/bin/env Rscript
dir <- getwd()
if (!is.null(dir)) {
	setwd(dir)
}


args <- commandArgs(trailing = TRUE)
number <- args[1]
filename_save <-args[2]


source('pcalg.R')
source('AllClasses.R')
source('Aaux.R')
source('JCI_FCI.R')
library(graph) 

# for python-style list comprehension
library(comprehenr)

# input synthetic data generated by GenerateInterventionalData.ipynb
df_list <- list()
for (i in 1:number) {
	df_list[[i]]<-read.csv(args[i+2],header = TRUE)
}


if (any(names(df_list[[1]])!=names(df_list[[2]]))) {
  stop("Input datasets columns not ordered!")
}

# Remove the latent confounders, L1 and L2
drops <- c("L1","L2")

# df1 <- subset(df1,select = -c("L1","L2"))
# df2 <- subset(df2,select = -c("L1","L2"))
env_list=list()
for (i in 1:number) {
	df_list[[i]]<-  df_list[[i]][ , !(names(df_list[[i]]) %in% drops)]
	env_list[[i]]=matrix(i,nrow=nrow(df_list[[i]]),ncol=1)
}


# Concatenate the datasets and create a dataset index vector
df=do.call(rbind,df_list)
env_index=do.call(rbind,env_list)

envs <- unique(env_index)
no_of_environments <- length(envs)
print(envs)

# Create F-nodes. 
# JCI uses one F node per environment.
# Design matrix allows using CI tests between F nodes for checking some invariances across interventional data. 

# Use tuples as subscripts to F node names:
F_envs <- 2:(no_of_environments)
# NA check required since even if i+1 is larger than no_of_env. comprehension assigns it unlike python
F_node_names <- to_list(for (i in F_envs) paste("F_",i-1,sep=''))
no_of_F_nodes <- length(F_node_names)
# Augment the data with F nodes and the corresponding values based on the design matrix.
F_vals <- matrix(0L,nrow=nrow(df),ncol=length(F_node_names))

for (i in 1:no_of_F_nodes){
  F_vals[env_index==F_envs[i],i]=1 # rows from the second environment assigned 1
}
colnames(F_vals)<-F_node_names
# col. number in updated data: ncol(gmInt)+

df <- cbind(df,F_vals)

# Now we are ready to pass data onto JCI_fci function with new variable names and F_node_names
# Assuming discrete data
# suffStat <- list(dm = df, adaptDF=FALSE)
# res <- JCI_fci(suffStat, indepTest=disCItest, skel.method='stable', labels = colnames(df),
#              alpha = 0.05, doPdsep = FALSE, F_node_names = F_node_names,verbose=TRUE)

# Burak's update: suppose Gaussian data. I will try to create my data and use it here. Hence, gaussCItest
suffStat <- list(dm = df, adaptDF=FALSE)
res <- JCI_fci(suffStat, indepTest=disCItest, skel.method='stable', labels = colnames(df),
             alpha = 0.05, doPdsep = FALSE, F_node_names = F_node_names,verbose=TRUE)


write.csv(res@amat,file=filename_save)
